### PR TITLE
Update ChangeAction.cs ushort issue.

### PR DESCRIPTION
**Pull request by SipanOhanyan**
Ushort <-> int mapping problem with entity framework.

### CODE REVIEW

**Comment by roadrunnerlenny** [comment]
Hi @SipanOhanyan ,
thanks for the fix! This will be part of the next version. Just released 1.8.7, so it probably will take a week or two until the next release. Do you need a pre-release version?

**Comment by SipanOhanyan** [comment]
It will be grateful.

**Comment by roadrunnerlenny** [comment]
Just released 1.8.8. alpha ( https://www.nuget.org/packages/ETLBox/1.8.8-alpha ) which contains the fix above.

**Comment by SipanOhanyan** [comment]
Thank you.

**Pull request merged**
