### PR TITLE
DbMerge enhancements, some simplifications and fixes

### PR DESCRIPTION
**Pull request by rolfik**

### CODE REVIEW

**Comment by anlennar** [comment]
Hi @rolfik ,
thanks for using ETLBox and your PR.  You proposing a lot of changes - could you explain what their intention is? I have some issues comparing old/new code because you made some rearrangements of code which caused to show a lot of insertions and deletions.

**Comment by rolfik** [comment]
> Hi @rolfik ,
> thanks for using ETLBox and your PR. You proposing a lot of changes - could you explain what their intention is? I have some issues comparing old/new code because you made some rearrangements of code which caused to show a lot of insertions and deletions.

Hello Andreas,
thank You for developing ETLBox.

I am working on our generic datawarehouse solution.
I use ASP.NET Core service to configure ETL/ELT pipelines to transfer data between databases.
After looking for current possibilities, I have found your ETLBox which I choose due to its DataFlow design.

Now I have this type of flow:
source -> transformation [-> add Source] -> target
where source is IDataFlowSource<S>, target is IDataFlowDestination<T> and transformation is (IDataFlowLinkTarget<S> target, IDataFlowLinkSource<T> source) (allowing me to chain more transformations}.

In one case DbDestination<T> is used as target in another one DbMerge<T> is used.
To allow it I had to add to IDataFlow(Batch)Destination<T>  to DbMerge<T> which was easy.
While looking through the code I started to do some optimizations in few constructors etc.
Than I thought, I could simplify constructors taking table name and connection manager.
I have changed TableDefinition a little so that TableName could be dropped from other constructors and just TableDefinition could be used.

- DbSource had: TableName, SourceTableDefinition and Sql
  - constructors now force you to choose either TableDefinition or Sql
  - SourceTableDefinition renamed to TableDefinition to be consistent
- DbDestination had: TableName, DestinationTableDefinition
  - constructors now force you to specify TableDefinition
  - DestinationTableDefinition renamed to TableDefinition to be consistent
- DbMerge had: TableName and unused TableDefinition
  - constructors now force you to specify TableDefinition with Name included
  - TableDefinition is used instead of TableName

TableData was optimized not to create List<T> instance to be soon replaced with another one

On other places null checking was removed and instead it was ensured it will never be null due to new checks in constructors (some parts of code cheched for null on a property, but other parts not).
...

These are just my suggestions.

Marek

**Comment by rolfik** [comment]
The next step I need is to enhance DbMerge to
- support some ExpandoObject wrapper
  - I want to specify just Id and some UpdateTime item properties and have other properties in dynamic object
- I need to figure out how to make data merging without fully loading items from target first
  - in my case I have source items which need to be inserted into target, but later may be updated in source so I need to synchronize them to identify only updates without deletions = updated items will be updated in target and other items from source will be inserted
  - so it should be enough to fetch only items from target with ids from source

**Comment by roadrunnerlenny** [comment]
Hi @rolfik ,
Thanks for you explanation. I really appreciate your effort. I just tried to go through all the changes you are proposing. Right now these are in totals in 150 files, which is quite a lot. So I looked through them for each commit - but some of them have refactoring/reordering or code styles adjustments, so that github removes and reinserts a block of the same lines which makes it hard to read and extract the real changes. 

Not quite sure how to go on to understand exactly what you did and why. For some things, I can see that they make sense (e.g. the commit `TableData uses BatchSize insted of DefaultBatchSize`  really fixes a bug and it's easy to understand). But for some parts, I don't really agree with the changes right now - (e.g. the use of default values in constructor just to reduce the amount of constructors is something which I wouldn't agree with). And some parts I don't understand what the advantage would be. 

I also noticed that you did a lot of modifications, but you didn't add a new test. I am not quite sure if all of the changes will be covered with the current tests. I tried to cover the most common use cases with the current tests, but I am quite sure that there is still a lot in my code that misses the appropriate test.

Finally, you want to merge into master - actually, the default branch is `dev`, and PRs should point to this branch. If you change the branch, you will probably see that there were also some changes on my side. 

Also,it is kind of irritating if you create a PR but the implementation isn't done - of course you can do this to give a preview, but then the title or a comment should at least say something like "this is a work in progress (WIP)". Otherwise the reviewer doesn't know when to start. 

Right now I am not quite sure how I could merge your changes. I really appreciate all your work. As I wrote, some of the changes are very good, and some of them I would like to discuss. But with this PR I don't see how to review them in a good and structured way. 

So right now I would suggest to close this PR and create a new one that contains much fewer changes. Perhaps we can start with the first commit? That would make it much easier to go through each one and merge them into the current code. 

Unless you have a better approach to go through the changes?

**Comment by rolfik** [comment]
Hi @roadrunnerlenny, thank You for comments.
For now I will close this pull request.
I will continue to work on our datawarehouse project using this library while extending it.
I do not have too much time to spare on new pull requests now so please feel free to use whatever You consider appropriate.

Thank You

Marek

**Comment by roadrunnerlenny** [comment]
Hi @rolfik ,

thank you for your feedback. I understand that this is additional work for you.
 
I just looked at the fork, I assume you will push your changes directly to the master branch? 

Of course I am still interested in your work and changes, and when I have some time to spare I can go through your commits and cherry-pick the changes that I would like to merge. So it would be great if you keep pushing your changes to your fork of the github project.

Good luck with your datawarehouse proejct!

**Comment by rolfik** [comment]
@roadrunnerlenny yes I will push changes to my fork`s `master` branch.

Thank You and have nice days.

**Pull request closed without merging**
